-- WAYPOINT intentionally ships without demo records.
-- Add only verified, source-backed rule packs and organisation data through
-- your own controlled migration process. Never treat fictional fixtures as law.
