import {randomId} from './id';
import type {Rule,RulePack,State,Shipment,Document,Product,Country} from '../types';
import {compile} from './engine';
const base:Pick<Rule,'version'|'country'|'direction'|'category'|'when'|'severity'|'sourceId'|'effectiveFrom'|'verifiedAt'>={version:'1.0',country:'ALL',direction:'all',category:'all',when:{all:[]},severity:'blocker',sourceId:'demo',effectiveFrom:'2026-01-01',verifiedAt:'2026-09-12'};
const rule=(id:string,title:string,stage:Rule['stage'],check:Rule['check'],extra:Partial<Rule>={}):Rule=>({...base,id,title,stage,check,message:title+' within the configured demonstration rules.',resolution:'Complete the missing information and recompile.',...extra});
export const common:Rule[]=[
rule('product','Complete product and shipment information','Product',{field:'valid',op:'equals',value:true}),
rule('classification','Classification confirmed','Classification',{all:[{field:'classification',op:'exists'},{field:'confirmed',op:'equals',value:true}]},{severity:'review',message:'A candidate classification must be confirmed by the exporter or a professional.',resolution:'Review the classification and confirm it, or request a consultant.'}),
rule('invoice','Commercial invoice available','Export requirements',{field:'docs.invoice',op:'equals',value:true},{documentType:'invoice',resolution:'Upload a commercial invoice.'}),
rule('origin','Manufacturing origin supported','Rules of origin',{field:'originSimple',op:'equals',value:true},{severity:'review',message:'Demo origin check: manufacture and export countries match, with at least 60% declared local content. This is a fictional threshold, not an AfCFTA origin determination.',resolution:'Provide manufacturing evidence and ask a consultant to review complex origin.'}),
rule('transport','Transport document available','Transport',{field:'docs.transport',op:'equals',value:true},{severity:'warning',documentType:'transport',resolution:'Add the transport document when the carrier issues it.'}),
rule('packing','Packing list available','Customs preparation',{field:'docs.packing',op:'equals',value:true},{documentType:'packing',resolution:'Upload a packing list.'}),
rule('expiry','Documents valid through shipping date','Customs preparation',{field:'expired',op:'equals',value:false},{severity:'warning',resolution:'Renew documents that expire before the planned shipping date.'}),
rule('value','High-value transaction review','Customs preparation',{field:'value',op:'lt',value:20000},{when:{field:'value',op:'gt',value:19999},severity:'review',message:'The fictional demonstration review threshold is USD 20,000 equivalent; currencies other than USD always require review.',resolution:'Ask a consultant to review the valuation.'}),
rule('currency','Currency supported for demo thresholds','Customs preparation',{field:'currency',op:'equals',value:'USD'},{severity:'review',resolution:'Ask a consultant to review currency conversion and value thresholds.'})];
const destination=(c:Country):Rule[]=>c==='KE'?[
rule('ke-compliance','Destination product documentation missing','Destination requirements',{field:'docs.compliance',op:'equals',value:true},{country:c,direction:'destination',version:'1.2',documentType:'compliance',message:'The Kenya demonstration pack requires destination product compliance evidence. This requirement is fictionalised for the demo.',resolution:'Attach the Kenya demo compliance document, or request professional review.'}),
rule('ke-label','Destination labelling information supplied','Destination requirements',{field:'packaging',op:'exists'},{country:c,direction:'destination'}),
rule('ke-importer','Destination importer identified','Destination requirements',{field:'importer',op:'exists'},{country:c,direction:'destination'})]:[
rule(c.toLowerCase()+'-declaration','Destination declaration available','Destination requirements',{field:'docs.declaration',op:'equals',value:true},{country:c,direction:'destination',documentType:'declaration',resolution:'Attach a destination declaration for this demonstration market.'}),
rule(c.toLowerCase()+'-buyer','Destination buyer identified','Destination requirements',{field:'importer',op:'exists'},{country:c,direction:'destination'})];
export const packs:RulePack[]=[{id:'CORE',name:'Shipment preparation foundation',country:'ALL',version:'1.0',published:'2026-09-12',status:'published',rules:common},...(['NG','GH','KE'] as Country[]).map(c=>({id:c+'-DEMO',name:({NG:'Nigeria',GH:'Ghana',KE:'Kenya'}[c])+' destination pack',country:c,version:c==='KE'?'1.2':'1.0',published:'2026-09-12',status:'published' as const,rules:destination(c)}))];
export const demoDoc=(type:string,country?:string):Document=>({id:randomId(),name:({invoice:'Commercial invoice',packing:'Packing list',compliance:'Product compliance certificate',declaration:'Destination declaration',transport:'Air waybill'}[type]??type)+' — DEMO.pdf',type,country,status:'available',demo:true,issued:'2026-09-01',expires:'2027-09-01'});
export const products:Product[]=[{id:'p1',name:'Natural Shea Body Butter',sku:'KN-SB-250',description:'Packaged shea body butter for retail sale, 250 ml jars.',category:'cosmetics',ingredients:'Shea butter, coconut oil, vitamin E',brand:'Kora Naturals',classification:'3304.99',manufactured:'NG'},{id:'p2',name:'African Black Soap',sku:'KN-AS-100',description:'Packaged cleansing bars for retail sale.',category:'cosmetics',ingredients:'Plant oils, cocoa pod ash',brand:'Kora Naturals',classification:'3401.11',manufactured:'NG'},{id:'p3',name:'Cotton Everyday Apparel',sku:'KN-CT-001',description:'Cotton knitted T-shirts.',category:'textiles',ingredients:'100% cotton',brand:'Kora Essentials',classification:'6109.10',manufactured:'NG'}];
export function makeShipment(i=0):Shipment {const p=products[i%3];return {id:i===0?'PSG-NG-KE-9K2M':'PSG-NG-'+(i%2?'GH':'KE')+'-'+String(1020+i),name:p.name,description:p.description,category:p.category,ingredients:p.ingredients,packaging:'Sealed retail jars in export cartons',brand:p.brand,classification:p.classification,confirmed:i!==11,manufactured:'NG',origin:'NG',destination:i%2?'GH':'KE',manufacturer:'Kora Naturals Ltd',localPercent:85,importer:i%2?'Accra Wellness Trading':'Nairobi Naturals Imports',purpose:'Commercial sale',quantity:i===0?500:120+i*30,unit:'cartons',weight:i===0?1600:400+i*80,value:i===0?12000:3200+i*650,currency:'USD',transport:'Air',shippingDate:'2026-10-15',documents:[demoDoc('invoice'),demoDoc('packing'),demoDoc('declaration','GH'),...(i>0&&i<7||i===11?[demoDoc('compliance','KE')]:[])],created:new Date(Date.UTC(2026,8,18-i)).toISOString(),draft:i===9||i===10};}
export function seed():State {const shipments=Array.from({length:12},(_,i)=>makeShipment(i));shipments[7].documents=shipments[7].documents.filter(d=>d.type!=='declaration');const compilations=shipments.filter(s=>!s.draft).map(s=>compile(s,packs,1,s.created));return {shipments,products:structuredClone(products),documents:[demoDoc('invoice'),demoDoc('packing'),{...demoDoc('company'),name:'Company registration — DEMO.pdf',expires:'2026-10-02'}],compilations,packs:structuredClone(packs),sources:[{id:'demo',organisation:'WAYPOINT demonstration team',title:'Fictional trade-preparation rule specification',reference:'WAYPOINT-DEMO-2026-09',jurisdiction:'NG / GH / KE',checked:'2026-09-12',notes:'DEMO / NOT FOR COMMERCIAL USE. These are authored test fixtures, not official legal requirements. Tariffs are not configured.'}],audit:shipments.map(s=>({id:randomId(),at:s.created,user:'Kora demo team',action:'Shipment created',entity:s.id,after:s.name})),notifications:[{id:'n1',title:'PSG-NG-KE-9K2M has one destination blocker',read:false,at:new Date().toISOString()},{id:'n2',title:'Company registration expires on 2 October',read:false,at:new Date().toISOString()}],organisation:{name:'Kora Naturals Ltd',country:'NG',address:'24 Adeola Odeku Street, Lagos',contact:'exports@kora.example',registration:'DEMO-RC-204892',tax:'DEMO-TAX-001'},reviews:[],invitations:[]};}
