import {PGlite} from '@electric-sql/pglite';import {beforeAll,afterAll,describe,it,expect} from 'vitest';import fs from 'node:fs';import {seed,makeShipment} from '../src/services/seed';
let db:PGlite;const admin='11111111-1111-4111-8111-111111111111';const outsider='22222222-2222-4222-8222-222222222222';let org:string;let state:ReturnType<typeof seed>;
beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;create function auth.role() returns text language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claim.role',true),''),'authenticated') $$;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;create function storage.foldername(name text) returns text[] language sql immutable as $$select string_to_array(name,'/')$$;grant usage on schema auth,storage,public to authenticated,service_role;grant execute on all functions in schema auth to authenticated,service_role;grant select,insert on storage.objects to authenticated;`);const sql=fs.readFileSync('supabase/migrations/202609190001_passage.sql','utf8').replace('create extension if not exists pgcrypto;','');await db.exec(sql);await db.query('insert into auth.users values($1,$2,now()),($3,$4,now())',[admin,'admin@demo.example',outsider,'outside@demo.example']);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[admin]);const result=await db.query<{id:string}>("select public.create_organisation('Kora test') as id");org=result.rows[0].id;state=seed();state.shipments=[];state.products=[];state.documents=[];state.compilations=[];state.audit=[];state.notifications=[];state.packs=[];state.sources=[];const organisation=await db.query<{data:typeof state.organisation}>('select data from organisations where id=$1',[org]);state.organisation=organisation.rows[0].data;},30000);
afterAll(async()=>{await db.close()});
describe.sequential('database access and immutable records',()=>{
 it('migration executes on PostgreSQL and authorises organisation admin',async()=>{const r=await db.query<{role:string}>('select member_role($1) as role',[org]);expect(r.rows[0].role).toBe('org_admin')});
 it('saves shipment transactionally and creates server audit',async()=>{const next=structuredClone(state);const s=makeShipment();s.documents=[];next.shipments.push(s);await db.query('select save_workspace($1,$2,$3)',[org,state,next]);state=next;const r=await db.query<{count:number}>('select count(*)::int as count from audit_logs where organisation_id=$1',[org]);expect(r.rows[0].count).toBeGreaterThan(0)});
 it('rejects outsider writes and hides organisation rows with RLS',async()=>{await db.query("select set_config('request.jwt.claim.sub',$1,false)",[outsider]);await db.exec('set role authenticated');const rows=await db.query('select * from shipments');expect(rows.rows).toHaveLength(0);await expect(db.query('select save_workspace($1,$2,$3)',[org,state,state])).rejects.toThrow('access denied');await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[admin])});
 it('rejects stale updates instead of silently losing another edit',async()=>{const next=structuredClone(state);next.shipments[0].name='Stale product';const stale=structuredClone(state);stale.shipments[0].name='Incorrect old value';await expect(db.query('select save_workspace($1,$2,$3)',[org,stale,next])).rejects.toThrow('Record changed')});
 it('organisation admin cannot publish global rules',async()=>{const next=structuredClone(state);next.packs=seed().packs;await expect(db.query('select save_workspace($1,$2,$3)',[org,state,next])).rejects.toThrow('Platform admin required')});
 it('normal user cannot forge compilation snapshot',async()=>{await expect(db.query('select record_compilation($1,$2,$3,$4)',[org,state.shipments[0].id,state.shipments[0],{}])).rejects.toThrow('Server compilation required')});
 it('exporter cannot self-approve documents or elevate invitations',async()=>{await db.query("update organisation_members set role='exporter' where user_id=$1",[admin]);const next=structuredClone(state);next.documents=[{id:'d1',name:'forged',type:'compliance',status:'available',demo:false}];await expect(db.query('select save_workspace($1,$2,$3)',[org,state,next])).rejects.toThrow('reviewer');const elevated=structuredClone(state);elevated.invitations=[{email:'person@example.com',role:'org_admin'}];await expect(db.query('select save_workspace($1,$2,$3)',[org,state,elevated])).rejects.toThrow('Organisation admin');await db.query("update organisation_members set role='org_admin' where user_id=$1",[admin])});
 it('audit rows cannot be rewritten even via privileged SQL',async()=>{await expect(db.exec("update audit_logs set data='{}'")).rejects.toThrow('Immutable record')});
 it('private storage isolation prevents another organisation from reading evidence',async()=>{await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['documents',org+'/test/evidence.pdf']);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[outsider]);await db.exec('set role authenticated');const rows=await db.query('select * from storage.objects');expect(rows.rows).toHaveLength(0);await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[admin])});
});
