import {describe,it,expect} from 'vitest';import {evaluate,compile,diff,selectPacks} from '../src/services/engine';import {seed,packs,makeShipment,demoDoc} from '../src/services/seed';import type {Condition} from '../src/types';
describe('condition evaluator',()=>{it.each<[Condition,Record<string,unknown>,boolean]>([
 [{field:'x',op:'equals',value:3},{x:3},true],[{field:'x',op:'not_equals',value:3},{x:4},true],[{field:'x',op:'in',value:['NG','GH']},{x:'NG'},true],[{field:'x',op:'gt',value:4},{x:5},true],[{field:'x',op:'lt',value:4},{x:3},true],[{field:'x',op:'exists'},{x:''},false],[{field:'x',op:'missing'},{},true],[{field:'x',op:'date_before',value:'2026-10-02'},{x:'2026-10-01'},true],[{field:'x',op:'date_after',value:'2026-10-02'},{x:'2026-10-03'},true],[{field:'x',op:'date_before',value:'2026-10-02'},{x:'bad'},false],[{all:[{field:'x',op:'equals',value:3},{any:[{field:'y',op:'equals',value:2},{field:'y',op:'equals',value:4}]}]},{x:3,y:4},true],
 ])('evaluates %j',(c,d,expected)=>expect(evaluate(c,d)).toBe(expected));});
describe('shipment compilation',()=>{
 it('exact hackathon blocker -> evidence -> recompile flow',()=>{const s=makeShipment();const before=compile(s,packs);expect(before.status).toBe('blocked');expect(before.blockers).toBe(1);expect(before.warnings).toBe(1);s.documents.push(demoDoc('compliance','KE'));const after=compile(s,packs,2);expect(after.status).toBe('warning');expect(after.blockers).toBe(0);expect(after.warnings).toBe(1);expect(after.completed).toBe(after.mandatory);expect(diff(before,after).resolved.map(r=>r.rule.id)).toEqual(['ke-compliance']);expect(before.shipment.documents.some(d=>d.type==='compliance')).toBe(false);});
 it('never treats uploaded, unreviewed evidence as satisfied',()=>{const s=makeShipment();s.documents.push({...demoDoc('compliance','KE'),status:'review'});expect(compile(s,packs).blockers).toBe(1)});
 it('Ghana scenario removes 3 and adds 2 requirements without mutating original',()=>{const s=makeShipment();const json=JSON.stringify(s);const before=compile(s,packs);const after=compile({...s,destination:'GH'},packs);expect(diff(before,after).removed).toHaveLength(3);expect(diff(before,after).added).toHaveLength(2);expect(JSON.stringify(s)).toBe(json);expect(after.results.some(r=>r.rule.id==='ke-compliance')).toBe(false)});
 it('does not reuse evidence for the wrong destination',()=>{const s=makeShipment();s.documents.push(demoDoc('compliance','GH'));expect(compile(s,packs).blockers).toBe(1)});
 it('requires human review when classification is unconfirmed',()=>{const s=makeShipment(11);const c=compile(s,packs);expect(c.reviews).toBeGreaterThan(0);expect(c.status).toBe('review')});
 it('missing rule coverage is never ready',()=>{const c=compile(makeShipment(),packs.filter(p=>p.country==='ALL'));expect(c.reviews).toBe(1);expect(c.status).toBe('review')});
 it('selects latest published pack without selecting a draft',()=>{const versions=[...packs,{...packs[3],version:'1.10'},{...packs[3],version:'1.11',status:'draft' as const}];expect(selectPacks(versions,makeShipment()).find(p=>p.id==='KE-DEMO')?.version).toBe('1.10')});
 it('snapshot stores rule content and versions independent of future pack edits',()=>{const copy=structuredClone(packs);const c=compile(makeShipment(),copy);const text=c.results[0].rule.title;copy[0].rules[0].title='Changed';expect(c.results[0].rule.title).toBe(text);expect(c.packs.find(p=>p.id==='KE-DEMO')?.version).toBe('1.2')});
 it('expired evidence creates warning; threshold and re-export create review',()=>{const s=makeShipment(2);s.documents[0].expires='2026-01-01';s.value=24000;s.manufactured='GH';const c=compile(s,packs);expect(c.warnings).toBe(2);expect(c.reviews).toBe(2)});
 it('seed distribution is six ready, three blocked, two drafts, one review',()=>{const s=seed();expect(s.shipments.filter(x=>x.draft)).toHaveLength(2);expect(s.compilations.filter(c=>['ready','warning'].includes(c.status))).toHaveLength(6);expect(s.compilations.filter(c=>c.status==='blocked')).toHaveLength(3);expect(s.compilations.filter(c=>c.status==='review')).toHaveLength(1)});
 it('nonpositive amounts produce a hard blocker',()=>{const s=makeShipment(2);s.value=0;expect(compile(s,packs).results.find(r=>r.rule.id==='product')?.passed).toBe(false)});
 it('rules outside their effective interval do not run',()=>{const copy=structuredClone(packs);copy[3].rules[0].effectiveFrom='2099-01-01';expect(compile(makeShipment(),copy).results.some(r=>r.rule.id==='ke-compliance')).toBe(false)});
});
