import {randomId} from '../services/id';
import {createContext,useContext,useState,useEffect,useCallback,type ReactNode} from 'react';
import type {State,Shipment,Compilation,Role,Document} from '../types';import {seed} from '../services/seed';import {compile} from '../services/engine';import {demo,supabase,loadWorkspace,saveWorkspace,memberships} from '../services/backend';
interface Store {state:State;role:Role;orgId:string;user:string;loading:boolean;error:string;toast:string;notify:(s:string)=>void;setRole:(r:Role)=>void;update:(fn:(s:State)=>void,action:string,entity?:string)=>Promise<void>;run:(s:Shipment)=>Promise<Compilation>;reset:()=>void;latest:(id:string)=>Compilation|undefined;attach:(id:string,d:Document)=>Promise<void>;switchOrg:(id:string)=>void;orgs:{organisation_id:string;role:Role;organisations:{name:string}}[];reload:()=>Promise<void>}
const Context=createContext<Store|null>(null);
export function StoreProvider({children}:{children:ReactNode}){const[state,setState]=useState<State>(seed);const[role,setRoleValue]=useState<Role>('org_admin');const[orgId,setOrgId]=useState('demo');const[user,setUser]=useState(demo?'Demo exporter':'');const[loading,setLoading]=useState(!demo);const[error,setError]=useState('');const[toast,setToast]=useState('');const[orgs,setOrgs]=useState<Store['orgs']>([]);
 const notify=useCallback((s:string)=>{setToast(s);setTimeout(()=>setToast(''),5000)},[]);
 const reload=useCallback(async()=>{if(demo)return;try{setLoading(true);if(!supabase)throw Error('Connect Supabase to use live accounts. Demo mode is available separately.');const{data}=await supabase.auth.getUser();setUser(data.user?.email??'');if(!data.user){setLoading(false);return}const ms=await memberships();setOrgs(ms);const m=ms.find(m=>m.organisation_id===orgId)??ms[0];if(!m)throw Error('No organisation membership. Ask an organisation administrator to add you.');setOrgId(m.organisation_id);setRoleValue(m.role);setState(await loadWorkspace(m.organisation_id));setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[orgId]);
 useEffect(()=>{void reload();const sub=supabase?.auth.onAuthStateChange(()=>{setTimeout(()=>void reload(),0)});return()=>sub?.data.subscription.unsubscribe()},[reload]);
 async function update(fn:(s:State)=>void,action:string,entity='workspace'){const next=structuredClone(state);fn(next);next.audit.unshift({id:randomId(),at:new Date().toISOString(),user,action,entity});try{if(!demo)await saveWorkspace(state,next,orgId);setState(next)}catch(e){notify('Save failed: '+(e as Error).message);throw e}}
 async function run(s:Shipment){let result:Compilation;const sequence=state.compilations.filter(c=>c.shipmentId===s.id).length+1;if(!demo){const{data,error}=await supabase!.functions.invoke('compile',{body:{shipmentId:s.id,organisationId:orgId}});if(error)throw error;result=data;await reload();}else{result=compile(s,state.packs,sequence);await update(n=>{n.compilations.push(result);const ship=n.shipments.find(x=>x.id===s.id);if(ship)ship.draft=false;n.notifications.unshift({id:randomId(),title:`${s.id}: ${result.blockers?result.blockers+' blocker detected':'compilation completed'}`,read:false,at:result.at})},'Compilation #'+sequence,s.id)}return result;}
 const latest=(id:string)=>state.compilations.filter(c=>c.shipmentId===id).sort((a,b)=>b.sequence-a.sequence)[0];
 return <Context.Provider value={{state,role,orgId,user,loading,error,toast,notify,setRole:r=>{if(demo)setRoleValue(r)},update,run,reset:()=>{if(demo){setState(seed());notify('Demonstration reset. The destination blocker is restored.')}},latest,attach:async(id,d)=>update(n=>{const s=n.shipments.find(s=>s.id===id);if(s)s.documents.push(d)},'Document attached',id),switchOrg:id=>setOrgId(id),orgs,reload}}>{children}</Context.Provider>
}
export const useStore=()=>{const c=useContext(Context);if(!c)throw Error('Missing workspace');return c};
