-- Waypoint official source-backed rule packs.
--
-- These are preparation checks, not legal advice. They deliberately use
-- review severity where the regulator requires product- or shipment-specific
-- interpretation. Do not add tariff values without a current classification
-- and official tariff lookup.

insert into public.rule_sources(id,data) values
('NEPC-EXPORT', '{"id":"NEPC-EXPORT","organisation":"Nigerian Export Promotion Council","title":"Export documents and procedures","reference":"Exporter registration, certificate of origin and export documents","url":"https://nepc.gov.ng/get-started/export-documents-procedures/","jurisdiction":"NG","checked":"2026-09-25","notes":"Official NEPC guidance. Confirm current process and document issuer before shipment."}'::jsonb),
('NEPC-EREG', '{"id":"NEPC-EREG","organisation":"Nigerian Export Promotion Council","title":"E-registration portal","reference":"Exporter certificate registration","url":"https://nepc.gov.ng/ereg/exporter","jurisdiction":"NG","checked":"2026-09-25","notes":"Official exporter registration portal."}'::jsonb),
('NAFDAC-FOOD-EXPORT', '{"id":"NAFDAC-FOOD-EXPORT","organisation":"National Agency for Food and Drug Administration and Control","title":"Food import and exports","reference":"Health certificate for processed and semi-processed food exports","url":"https://nafdac.gov.ng/food/food-import-exports/","jurisdiction":"NG","checked":"2026-09-25","notes":"Official NAFDAC guidance. Product eligibility and laboratory/inspection steps require confirmation."}'::jsonb),
('NAFDAC-COSMETICS', '{"id":"NAFDAC-COSMETICS","organisation":"National Agency for Food and Drug Administration and Control","title":"Cosmetics guidelines","reference":"Cosmetics registration and regulatory guidance","url":"https://nafdac.gov.ng/cosmetics-medical-devices/cosmetics-guidelines/","jurisdiction":"NG","checked":"2026-09-25","notes":"Official NAFDAC guidance. This check does not determine classification or approval."}'::jsonb),
('GRA-IMPORT', '{"id":"GRA-IMPORT","organisation":"Ghana Revenue Authority Customs Division","title":"Import procedures","reference":"Documents required for clearing imported goods","url":"https://gra.gov.gh/customs/import-procedures/","jurisdiction":"GH","checked":"2026-09-25","notes":"Official GRA customs guidance lists waybill/bill of lading, attested invoice, packing list and IDF."}'::jsonb),
('GRA-EXPORT', '{"id":"GRA-EXPORT","organisation":"Ghana Revenue Authority Customs Division","title":"Export procedures","reference":"Electronic customs declaration and supporting permits","url":"https://gra.gov.gh/customs/export-procedures/","jurisdiction":"GH","checked":"2026-09-25","notes":"Official GRA customs guidance. Confirm current ICUMS workflow with a licensed agent."}'::jsonb),
('FDA-GH-COSMETICS', '{"id":"FDA-GH-COSMETICS","organisation":"Ghana Food and Drugs Authority","title":"Cosmetics and household chemicals","reference":"Product registration and imported-product guidance","url":"https://fdaghana.gov.gh/services-2/product-registration/cosmetics-household-chemicals/","jurisdiction":"GH","checked":"2026-09-25","notes":"Official FDA Ghana guidance. Registration pathway depends on product and importer context."}'::jsonb),
('FDA-GH-FOOD', '{"id":"FDA-GH-FOOD","organisation":"Ghana Food and Drugs Authority","title":"Food registration","reference":"Food product registration and market authorization","url":"https://fdaghana.gov.gh/services-2/product-registration/food-registration/","jurisdiction":"GH","checked":"2026-09-25","notes":"Official FDA Ghana food registration page."}'::jsonb),
('KRA-IMPORT', '{"id":"KRA-IMPORT","organisation":"Kenya Revenue Authority","title":"How to import","reference":"Import clearance, commercial invoice and clearing agent guidance","url":"https://www.kra.go.ke/individual/importing/learn-about-importation/how-to-import","jurisdiction":"KE","checked":"2026-09-25","notes":"Official KRA guidance. Clearance requirements vary by goods and entry route."}'::jsonb),
('KRA-COO-2025', '{"id":"KRA-COO-2025","organisation":"Kenya Revenue Authority","title":"Mandatory certificate of origin on imports","reference":"Public notice effective 1 July 2025","url":"https://www.kra.go.ke/news-center/public-notices/2303-requirement-for-mandatory-certificate-of-origin-on-imports-into-kenya","jurisdiction":"KE","checked":"2026-09-25","notes":"Official KRA public notice. Exceptions and alternative evidence require Customs verification."}'::jsonb),
('KEBS-PVOC', '{"id":"KEBS-PVOC","organisation":"Kenya Bureau of Standards","title":"Pre-export verification of conformity","reference":"Certificate of Conformity used for cargo clearance","url":"https://www.kebs.org/pre-export-verification-of-conformity/","jurisdiction":"KE","checked":"2026-09-25","notes":"Official KEBS PVoC guidance. Applicability is product- and scope-dependent."}'::jsonb),
('PPB-KE-COSMETICS', '{"id":"PPB-KE-COSMETICS","organisation":"Pharmacy and Poisons Board Kenya","title":"Market authorisation and registration","reference":"Regulated health products and cosmetics pathway","url":"https://web.pharmacyboardkenya.org/registrationretentionvariations/","jurisdiction":"KE","checked":"2026-09-25","notes":"Official PPB portal. Confirm whether the formulation is regulated by PPB or another Kenyan authority."}'::jsonb),
('WAYPOINT-COVERAGE', '{"id":"WAYPOINT-COVERAGE","organisation":"Waypoint","title":"Official-source coverage notice","reference":"Coverage and professional-review fallback","jurisdiction":"ALL","checked":"2026-09-25","notes":"Internal control: missing coverage is never treated as approval. A qualified professional must verify unsupported combinations."}'::jsonb)
on conflict(id) do update set data=excluded.data,updated_at=now();

insert into public.rule_packs(id,version,data) values
('NG-OFFICIAL','1.0','{"id":"NG-OFFICIAL","name":"Nigeria official preparation pack","country":"NG","version":"1.0","published":"2026-09-25","status":"published","sourceType":"official","rules":[
 {"id":"NG-NEPC-EXPORTER","version":"1.0","country":"NG","direction":"origin","category":"all","stage":"Export requirements","when":{"all":[{"field":"origin","op":"equals","value":"NG"}]},"check":{"field":"docs.nepc-exporter-certificate","op":"exists"},"severity":"blocker","title":"Nigeria exporter certificate required","message":"NEPC identifies exporter registration and an exporter certificate as the first step for Nigerian exporters.","resolution":"Upload the current NEPC exporter certificate or obtain professional confirmation that an exception applies.","documentType":"nepc-exporter-certificate","sourceId":"NEPC-EXPORT","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"},
 {"id":"NG-CERTIFICATE-ORIGIN","version":"1.0","country":"NG","direction":"origin","category":"all","stage":"Rules of origin","when":{"all":[{"field":"origin","op":"equals","value":"NG"}]},"check":{"field":"docs.certificate-of-origin","op":"exists"},"severity":"review","title":"Certificate of origin should be verified","message":"NEPC describes a certificate of origin as evidence of the origin of goods and notes its relevance to trade-agreement benefits.","resolution":"Confirm the destination and agreement pathway with a qualified trade professional, then upload the appropriate origin evidence.","documentType":"certificate-of-origin","sourceId":"NEPC-EXPORT","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"},
 {"id":"NG-NAFDAC-COSMETICS","version":"1.0","country":"NG","direction":"origin","category":"cosmetics","stage":"Export requirements","when":{"all":[{"field":"origin","op":"equals","value":"NG"}]},"check":{"field":"docs.nafdac-cosmetics-registration","op":"exists"},"severity":"review","title":"Confirm NAFDAC cosmetics status","message":"NAFDAC publishes cosmetics registration guidance. Product status depends on formulation, claims and the intended export pathway.","resolution":"Have the formulation and label reviewed against current NAFDAC guidance; upload the relevant registration or professional determination.","documentType":"nafdac-cosmetics-registration","sourceId":"NAFDAC-COSMETICS","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"},
 {"id":"NG-NAFDAC-FOOD","version":"1.0","country":"NG","direction":"origin","category":"food","stage":"Export requirements","when":{"all":[{"field":"origin","op":"equals","value":"NG"}]},"check":{"field":"docs.nafdac-food-health-certificate","op":"exists"},"severity":"review","title":"Confirm NAFDAC food export certificate","message":"NAFDAC provides a health-certificate pathway for processed and semi-processed food exports.","resolution":"Confirm eligibility, inspection and laboratory steps with NAFDAC or a licensed professional, then upload the current evidence.","documentType":"nafdac-food-health-certificate","sourceId":"NAFDAC-FOOD-EXPORT","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"}
]}'::jsonb),
('GH-OFFICIAL','1.0','{"id":"GH-OFFICIAL","name":"Ghana official preparation pack","country":"GH","version":"1.0","published":"2026-09-25","status":"published","sourceType":"official","rules":[
 {"id":"GH-IMPORT-WAYBILL","version":"1.0","country":"GH","direction":"destination","category":"all","stage":"Destination requirements","when":{"all":[{"field":"destination","op":"equals","value":"GH"}]},"check":{"field":"docs.transport-document","op":"exists"},"severity":"blocker","title":"Ghana transport document required","message":"GRA lists an original waybill or bill of lading among the documents for import clearance.","resolution":"Upload the applicable original waybill, airway bill or bill of lading and have the entry checked by a licensed agent.","documentType":"transport-document","sourceId":"GRA-IMPORT","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"},
 {"id":"GH-IMPORT-INVOICE","version":"1.0","country":"GH","direction":"destination","category":"all","stage":"Customs preparation","when":{"all":[{"field":"destination","op":"equals","value":"GH"}]},"check":{"field":"docs.attested-invoice","op":"exists"},"severity":"blocker","title":"Attested invoice required for Ghana clearance","message":"GRA lists an attested invoice among the documents required before or when imported goods arrive.","resolution":"Upload the attested commercial invoice or confirm the accepted invoice format with Ghana Customs.","documentType":"attested-invoice","sourceId":"GRA-IMPORT","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"},
 {"id":"GH-IMPORT-PACKING","version":"1.0","country":"GH","direction":"destination","category":"all","stage":"Customs preparation","when":{"all":[{"field":"destination","op":"equals","value":"GH"}]},"check":{"field":"docs.packing-list","op":"exists"},"severity":"blocker","title":"Packing list required for Ghana clearance","message":"GRA lists a packing list among the documents required for import clearance.","resolution":"Upload the shipment packing list and ensure its quantities agree with the invoice.","documentType":"packing-list","sourceId":"GRA-IMPORT","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"},
 {"id":"GH-IMPORT-IDF","version":"1.0","country":"GH","direction":"destination","category":"all","stage":"Destination requirements","when":{"all":[{"field":"destination","op":"equals","value":"GH"}]},"check":{"field":"docs.import-declaration-form","op":"exists"},"severity":"review","title":"Ghana Import Declaration Form","message":"GRA lists an Import Declaration Form from the Ministry of Trade for import clearance.","resolution":"Ask the importer or licensed clearing agent to obtain and attach the current IDF.","documentType":"import-declaration-form","sourceId":"GRA-IMPORT","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"},
 {"id":"GH-COSMETICS-REGISTRATION","version":"1.0","country":"GH","direction":"destination","category":"cosmetics","stage":"Destination requirements","when":{"all":[{"field":"destination","op":"equals","value":"GH"}]},"check":{"field":"docs.ghana-fda-cosmetics-registration","op":"exists"},"severity":"review","title":"Ghana FDA cosmetics registration","message":"FDA Ghana provides registration forms and guidance for cosmetics and household chemicals, including imported products.","resolution":"Confirm the importer and product registration pathway with FDA Ghana; upload the registration evidence or professional review note.","documentType":"ghana-fda-cosmetics-registration","sourceId":"FDA-GH-COSMETICS","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"},
 {"id":"GH-FOOD-REGISTRATION","version":"1.0","country":"GH","direction":"destination","category":"food","stage":"Destination requirements","when":{"all":[{"field":"destination","op":"equals","value":"GH"}]},"check":{"field":"docs.ghana-fda-food-registration","op":"exists"},"severity":"review","title":"Ghana FDA food registration","message":"FDA Ghana describes registration and market authorization for food products intended for sale in Ghana.","resolution":"Confirm the product registration route with FDA Ghana or the importer, then upload the certificate or review record.","documentType":"ghana-fda-food-registration","sourceId":"FDA-GH-FOOD","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"},
 {"id":"GH-EXPORT-DECLARATION","version":"1.0","country":"GH","direction":"origin","category":"all","stage":"Export requirements","when":{"all":[{"field":"origin","op":"equals","value":"GH"}]},"check":{"field":"docs.customs-export-declaration","op":"exists"},"severity":"review","title":"Ghana electronic export declaration","message":"GRA says traditional exports use an electronic Customs Declaration submitted through ICUMS with supporting certificates and permits.","resolution":"Confirm the current ICUMS export filing with the exporter or licensed agent and attach the declaration when available.","documentType":"customs-export-declaration","sourceId":"GRA-EXPORT","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"}
]}'::jsonb),
('KE-OFFICIAL','1.0','{"id":"KE-OFFICIAL","name":"Kenya official preparation pack","country":"KE","version":"1.0","published":"2026-09-25","status":"published","sourceType":"official","rules":[
 {"id":"KE-CERTIFICATE-ORIGIN","version":"1.0","country":"KE","direction":"destination","category":"all","stage":"Rules of origin","when":{"all":[{"field":"destination","op":"equals","value":"KE"}]},"check":{"field":"docs.certificate-of-origin","op":"exists"},"severity":"blocker","title":"Kenya certificate of origin","message":"KRA published a notice requiring a Certificate of Origin for imports into Kenya, effective 1 July 2025, subject to stated exceptions.","resolution":"Upload the certificate of origin or have Customs confirm an accepted exception or alternative document.","documentType":"certificate-of-origin","sourceId":"KRA-COO-2025","effectiveFrom":"2025-07-01","verifiedAt":"2026-09-25"},
 {"id":"KE-COMMERCIAL-INVOICE","version":"1.0","country":"KE","direction":"destination","category":"all","stage":"Customs preparation","when":{"all":[{"field":"destination","op":"equals","value":"KE"}]},"check":{"field":"docs.commercial-invoice","op":"exists"},"severity":"blocker","title":"Kenya commercial invoice","message":"KRA import guidance requires valid commercial invoices as part of import preparation.","resolution":"Upload the signed commercial invoice and ensure the value, currency, seller and buyer match the shipment.","documentType":"commercial-invoice","sourceId":"KRA-IMPORT","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"},
 {"id":"KE-PACKING-LIST","version":"1.0","country":"KE","direction":"destination","category":"all","stage":"Customs preparation","when":{"all":[{"field":"destination","op":"equals","value":"KE"}]},"check":{"field":"docs.packing-list","op":"exists"},"severity":"blocker","title":"Kenya packing list","message":"KRA customs guidance lists a packing list among documents used for import/export clearance.","resolution":"Upload the packing list and reconcile quantities and weights with the shipment.","documentType":"packing-list","sourceId":"KRA-IMPORT","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"},
 {"id":"KE-PVOC-COC","version":"1.0","country":"KE","direction":"destination","category":"all","stage":"Destination requirements","when":{"all":[{"field":"destination","op":"equals","value":"KE"}]},"check":{"field":"docs.certificate-of-conformity","op":"exists"},"severity":"review","title":"Check Kenya PVoC / Certificate of Conformity","message":"KEBS states that KRA uses a Certificate of Conformity as a cargo-clearance reference, with scope and applicability depending on the goods.","resolution":"Ask the appointed PVoC agent or licensed professional whether the goods are in scope, then attach the CoC or written determination.","documentType":"certificate-of-conformity","sourceId":"KEBS-PVOC","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"},
 {"id":"KE-COSMETICS-AUTH","version":"1.0","country":"KE","direction":"destination","category":"cosmetics","stage":"Destination requirements","when":{"all":[{"field":"destination","op":"equals","value":"KE"}]},"check":{"field":"docs.kenya-cosmetics-market-authorisation","op":"exists"},"severity":"review","title":"Confirm Kenya cosmetics market authorisation","message":"The Pharmacy and Poisons Board lists cosmetics within its regulated product registration and market-authorisation work, but the correct authority depends on the formulation and claims.","resolution":"Have the importer or qualified Kenyan regulatory professional confirm the authority and attach the applicable authorisation or review note.","documentType":"kenya-cosmetics-market-authorisation","sourceId":"PPB-KE-COSMETICS","effectiveFrom":"2026-01-01","verifiedAt":"2026-09-25"}
]}'::jsonb)
on conflict(id,version) do nothing;

